name: "DiligentGraphics: Install Doxygen"
description: "Downloads and installs Doxygen"

inputs:
  version:
    description: Doxygen version to install
    required: false
    default: '1.13.2'

runs:
  using: "composite" # must be set to "composite"
  steps:
    - name: Download Doxygen
      shell: bash
      run: |
        # Download and install Doxygen
        DOXYGEN_VERSION=${{ inputs.version }}
        wget https://doxygen.nl/files/doxygen-$DOXYGEN_VERSION.linux.bin.tar.gz
        tar -xzf doxygen-$DOXYGEN_VERSION.linux.bin.tar.gz
        sudo cp -r doxygen-$DOXYGEN_VERSION/bin/* /usr/local/bin/
        rm -rf doxygen-$DOXYGEN_VERSION*
        doxygen --version
