name: "DiligentGraphics: Setup Build Environment"
description: "Download build prerequisites and set up the environment"

inputs:
  platform:
    description: Target platform (Win32, UWP, Linux, Android, MacOS, iOS, tvOS or Emscripten)
    required: true

  vulkan-sdk-version:
    description: Vulkan SDK version
    required: false
    default: '1.3.204.1'

  java-version:
    description: Java version
    required: false
    default: '17'

  emsdk-version:
    description: Emscripten SDK version
    required: false
    default: '3.1.9'

  setup-ninja:
    description: Whether to set up Ninja
    required: false
    default: 'false'

  ninja-vs-arch:
    description: Ninja architecture for Visual Studio build (x64 or Win32)
    required: false
    default: 'x64'

runs:
  using: "composite" # must be set to "composite"
  steps:
    - name: Set Environment Variables
      shell: bash
      run: |
        echo "DILIGENT_TARGET_PLATFORM=${{inputs.platform}}" >> $GITHUB_ENV

    - name: Download Linux dependencies
      if: ${{ inputs.platform == 'Linux' }}
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install build-essential libx11-dev libgl1-mesa-dev
        if [[ "${{ endsWith(github.repository, 'Samples') || endsWith(github.repository, 'Engine') }}" == "true" ]]; then
          sudo apt-get install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
        fi

    - name: Setup Ninja
      if: ${{ success() && (inputs.setup-ninja == 'true' || inputs.platform == 'Emscripten') }}
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Setup VS Development Environment for Ninja
      if: ${{ success() && inputs.setup-ninja == 'true' && runner.os == 'Windows' }}
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ inputs.ninja-vs-arch }}

    - name: Download Vulkan SDK
      if: ${{ success() && (inputs.platform == 'MacOS' || inputs.platform == 'iOS' || inputs.platform == 'tvOS') }}
      working-directory: ${{github.action_path}}
      shell: bash
      run: |
        chmod +x vulkan_sdk.sh
        ./vulkan_sdk.sh ${{inputs.vulkan-sdk-version}}

    - name: Set up Java
      if: ${{ success() && inputs.platform == 'Android' }}
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}

    - name: Setup Emscripten SDK
      if: ${{ success() && inputs.platform == 'Emscripten' }}
      uses: mymindstorm/setup-emsdk@master
      with:
        version: ${{ inputs.emsdk-version }}
