name: "DiligentGraphics: Run Core GPU Tests"
description: "Run tests from the DiligentCoreAPITest suite"

inputs:
  mode:
    description: Graphics mode (d3d11_sw, d3d12_sw)
    required: true

  use-dxc:
    description: Whether to use DXC compiler
    default: "false"
    required: false

  non-separable-progs:
    description: Whether to force non-separable OpenGL programs
    default: "false"
    required: false

  vk-compatibility:
    description: Whether to run tests in Vulkan compatibility mode
    default: "false"
    required: false

  args:
    description: Optional extra arguments to pass to the test
    required: false

runs:
  using: "composite" # must be set to "composite"

  steps:
    - name: Run Diligent Core GPU Tests
      working-directory: ${{github.workspace}}
      env:
        INPUT_RUNNER_OS:     ${{runner.os}}
        INPUT_MODE:          ${{inputs.mode}}
        INPUT_USE_DXC:       ${{inputs.use-dxc}}
        INPUT_NON_SEP_PROGS: ${{inputs.non-separable-progs}}
        INPUT_VK_COMPAT:     ${{inputs.vk-compatibility}}
        INPUT_ARGS:          ${{inputs.args}}
        INPUT_IS_SUBMODULE:  ${{!endsWith(github.repository, 'Core')}}
      shell: bash
      run: |
        # Diligent Core GPU Tests
        chmod +x "${{github.action_path}}/run_core_gpu_tests.sh"
        "${{github.action_path}}/run_core_gpu_tests.sh"

    - name: Verify Test Output
      if: success()
      env:
        INPUT_MODE:          ${{inputs.mode}}
        INPUT_USE_DXC:       ${{inputs.use-dxc}}
        INPUT_NON_SEP_PROGS: ${{inputs.non-separable-progs}}
        INPUT_VK_COMPAT:     ${{inputs.vk-compatibility}}
      shell: bash
      run: |
        # Verify Test Output
        chmod +x "${{github.action_path}}/verify_test_output.sh"
        EXIT_CODE=0
        "${{github.action_path}}/verify_test_output.sh" || EXIT_CODE=$?
        if [[ "$EXIT_CODE" != "0" ]]; then
          echo "::error:: Core GPU tests output verification failed! Please examine it to find mismatches."
        fi
