name: "DiligentGraphics: Run Sample Tests"
description: "Run sample and tutorial tests"

inputs:
  mode:
    description: 'Test mode (e.g. d3d11, d3d12_sw, gl, etc.)'
    required: true

  golden-image-mode:
    description: 'Golden image processing mode: "compare" (default), "capture", or "compare_update"'
    required: false
    default: 'compare'

  non-separable-progs:
    description: Whether to force non-separable OpenGL programs
    required: false
    default: 'false'

  vk-compatibility:
    description: Whether to run tests in Vulkan compatibility mode
    required: false
    default: 'false'

runs:
  using: "composite" # must be set to "composite"

  steps:
    - name: Windows Tests
      if: ${{ runner.os == 'Windows' }}
      working-directory: ${{github.workspace}}/DiligentSamples/Tests
      shell: cmd
      run: |
        :: Sample Tests
        set args=--mode ${{inputs.mode}}
        if "${{inputs.non-separable-progs}}" == "true" (
          set args=%args% --non_separable_progs 1
        )
        if "${{inputs.vk-compatibility}}" == "true" (
          set args=%args% --vk_compatibility 1
        )
        ProcessGoldenImages.bat "${{github.workspace}}/DiligentTestData/GoldenImages" ${{inputs.golden-image-mode}} "%args%"

    - name: Linux Tests
      if: ${{ runner.os == 'Linux' }}
      working-directory: ${{github.workspace}}/DiligentSamples/Tests
      shell: bash
      run: |
        # Sample Tests
        args="--mode ${{inputs.mode}}"
        if [[ "${{inputs.non-separable-progs}}" == "true" ]]; then
          args="$args --non_separable_progs 1"
        fi
        if [[ "${{inputs.vk-compatibility}}" == "true" ]]; then
          args="$args --vk_compatibility 1"
        fi
        chmod +x ./ProcessGoldenImages.sh
        ./ProcessGoldenImages.sh "${{github.workspace}}/DiligentTestData/GoldenImages" ${{inputs.golden-image-mode}} "$args"
